name = "cloudflare-saas-stack"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".next"

[build]
command = "npm run build"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "cfsaas-db"
database_id = "97b18814-4bf6-44fe-9630-d172eeebd1c6"
migrations_dir = "./drizzle"
