name = "cloudflare-saas-stack"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".next"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "cf_saas-db"
database_id = "bba6a9f4-2357-4474-9150-bea37ac24654"
migrations_dir = "./drizzle"
